# Generated by Django 5.0 on 2026-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('rol', models.CharField(max_length=30)),
                ('mean', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=30)),
                ('is_tutor', models.BooleanField()),
            ],
        ),
    ]
